site_name: KtorMonitor
site_description: 'Powerful tool to monitor Ktor Client requests and responses, making it easier to debug and analyze network communication.'
site_author: 'Cosmin Mihu'
site_url: https://github.com/CosminMihuMDC/KtorMonitor

repo_name: 'KtorMonitor'
repo_url: 'https://github.com/CosminMihuMDC/KtorMonitor'

copyright: © 2026 Cosmin Mihu

theme:

  name: material
  custom_dir: overrides

  language: 'en'
  favicon: 'images/logo-icon.svg'
  logo: 'images/logo-icon.svg'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

  palette: 

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep purple
      accent: indigo    

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: indigo    

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: deep purple
      accent: indigo 

extra:
  social:
    - icon: simple/ktor
      link: https://ktor.io/docs/
    - icon: material/coffee
      link: https://www.buymeacoffee.com/cosminmihu
    - icon: material/github
      link: https://github.com/CosminMihuMDC/KtorMonitor

nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Integration': integration.md
  - 'API ⏏': api/
  - 'Contributing': contributing.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true